// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { EAggregateType, EAggregateTypeFromJSON, EAggregateTypeFromJSONTyped, EAggregateTypeToJSON } from "./";

/**
 *
 * @export
 * @interface AggregateKeyInfo
 */
export interface AggregateKeyInfo {
  /**
   *
   * @type {string}
   * @memberof AggregateKeyInfo
   */
  key?: string | null;
  /**
   *
   * @type {EAggregateType}
   * @memberof AggregateKeyInfo
   */
  aggregateType?: EAggregateType;
}

export function AggregateKeyInfoFromJSON(json: any): AggregateKeyInfo {
  return AggregateKeyInfoFromJSONTyped(json, false);
}

export function AggregateKeyInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateKeyInfo {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    key: !exists(json, "key") ? undefined : json["key"],
    aggregateType: !exists(json, "aggregateType") ? undefined : EAggregateTypeFromJSON(json["aggregateType"])
  };
}

export function AggregateKeyInfoToJSON(value?: AggregateKeyInfo | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    key: value.key,
    aggregateType: EAggregateTypeToJSON(value.aggregateType)
  };
}
