// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthenticateDto
 */
export interface AuthenticateDto {
  /**
   *
   * @type {string}
   * @memberof AuthenticateDto
   */
  userName?: string | null;
  /**
   *
   * @type {string}
   * @memberof AuthenticateDto
   */
  password?: string | null;
}

export function AuthenticateDtoFromJSON(json: any): AuthenticateDto {
  return AuthenticateDtoFromJSONTyped(json, false);
}

export function AuthenticateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userName: !exists(json, "userName") ? undefined : json["userName"],
    password: !exists(json, "password") ? undefined : json["password"]
  };
}

export function AuthenticateDtoToJSON(value?: AuthenticateDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userName: value.userName,
    password: value.password
  };
}
