// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum EAggregateType {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_3 = 3
}

export function EAggregateTypeFromJSON(json: any): EAggregateType {
  return EAggregateTypeFromJSONTyped(json, false);
}

export function EAggregateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EAggregateType {
  return json as EAggregateType;
}

export function EAggregateTypeToJSON(value?: EAggregateType | null): any {
  return value as any;
}
