// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum EOrderStatusCode {
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_3 = 3,
  NUMBER_4 = 4
}

export function EOrderStatusCodeFromJSON(json: any): EOrderStatusCode {
  return EOrderStatusCodeFromJSONTyped(json, false);
}

export function EOrderStatusCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EOrderStatusCode {
  return json as EOrderStatusCode;
}

export function EOrderStatusCodeToJSON(value?: EOrderStatusCode | null): any {
  return value as any;
}
