// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { EOrderStatusCode, EOrderStatusCodeFromJSON, EOrderStatusCodeFromJSONTyped, EOrderStatusCodeToJSON } from "./";

/**
 *
 * @export
 * @interface OrderDetailDto
 */
export interface OrderDetailDto {
  /**
   *
   * @type {EOrderStatusCode}
   * @memberof OrderDetailDto
   */
  orderStatusCode?: EOrderStatusCode;
  /**
   *
   * @type {number}
   * @memberof OrderDetailDto
   */
  orderId?: number;
  /**
   *
   * @type {Date}
   * @memberof OrderDetailDto
   */
  startDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof OrderDetailDto
   */
  endDate?: Date;
  /**
   *
   * @type {string}
   * @memberof OrderDetailDto
   */
  comment?: string | null;
  /**
   *
   * @type {number}
   * @memberof OrderDetailDto
   */
  orderStatusId?: number;
  /**
   *
   * @type {string}
   * @memberof OrderDetailDto
   */
  createdBy?: string | null;
  /**
   *
   * @type {Date}
   * @memberof OrderDetailDto
   */
  createdOn?: Date;
  /**
   *
   * @type {string}
   * @memberof OrderDetailDto
   */
  updatedBy?: string | null;
  /**
   *
   * @type {Date}
   * @memberof OrderDetailDto
   */
  updatedOn?: Date;
}

export function OrderDetailDtoFromJSON(json: any): OrderDetailDto {
  return OrderDetailDtoFromJSONTyped(json, false);
}

export function OrderDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDetailDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orderStatusCode: !exists(json, "orderStatusCode") ? undefined : EOrderStatusCodeFromJSON(json["orderStatusCode"]),
    orderId: !exists(json, "orderId") ? undefined : json["orderId"],
    startDate: !exists(json, "startDate") ? undefined : new Date(json["startDate"]),
    endDate: !exists(json, "endDate") ? undefined : new Date(json["endDate"]),
    comment: !exists(json, "comment") ? undefined : json["comment"],
    orderStatusId: !exists(json, "orderStatusId") ? undefined : json["orderStatusId"],
    createdBy: !exists(json, "createdBy") ? undefined : json["createdBy"],
    createdOn: !exists(json, "createdOn") ? undefined : new Date(json["createdOn"]),
    updatedBy: !exists(json, "updatedBy") ? undefined : json["updatedBy"],
    updatedOn: !exists(json, "updatedOn") ? undefined : new Date(json["updatedOn"])
  };
}

export function OrderDetailDtoToJSON(value?: OrderDetailDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    orderStatusCode: EOrderStatusCodeToJSON(value.orderStatusCode),
    orderId: value.orderId,
    startDate: value.startDate === undefined ? undefined : value.startDate.toISOString(),
    endDate: value.endDate === undefined ? undefined : value.endDate.toISOString(),
    comment: value.comment,
    orderStatusId: value.orderStatusId,
    createdBy: value.createdBy,
    createdOn: value.createdOn === undefined ? undefined : value.createdOn.toISOString(),
    updatedBy: value.updatedBy,
    updatedOn: value.updatedOn === undefined ? undefined : value.updatedOn.toISOString()
  };
}
