// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { OrderGridDto, OrderGridDtoFromJSON, OrderGridDtoFromJSONTyped, OrderGridDtoToJSON } from "./";

/**
 *
 * @export
 * @interface OrderGridDtoPaginatedResults
 */
export interface OrderGridDtoPaginatedResults {
  /**
   *
   * @type {number}
   * @memberof OrderGridDtoPaginatedResults
   */
  currentPage?: number;
  /**
   *
   * @type {number}
   * @memberof OrderGridDtoPaginatedResults
   */
  pageSize?: number;
  /**
   *
   * @type {number}
   * @memberof OrderGridDtoPaginatedResults
   */
  totalCount?: number;
  /**
   *
   * @type {number}
   * @memberof OrderGridDtoPaginatedResults
   */
  readonly nbPages?: number;
  /**
   *
   * @type {number}
   * @memberof OrderGridDtoPaginatedResults
   */
  readonly nbIemsOnCurrentPage?: number;
  /**
   *
   * @type {Array<OrderGridDto>}
   * @memberof OrderGridDtoPaginatedResults
   */
  results?: Array<OrderGridDto> | null;
}

export function OrderGridDtoPaginatedResultsFromJSON(json: any): OrderGridDtoPaginatedResults {
  return OrderGridDtoPaginatedResultsFromJSONTyped(json, false);
}

export function OrderGridDtoPaginatedResultsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OrderGridDtoPaginatedResults {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    currentPage: !exists(json, "currentPage") ? undefined : json["currentPage"],
    pageSize: !exists(json, "pageSize") ? undefined : json["pageSize"],
    totalCount: !exists(json, "totalCount") ? undefined : json["totalCount"],
    nbPages: !exists(json, "nbPages") ? undefined : json["nbPages"],
    nbIemsOnCurrentPage: !exists(json, "nbIemsOnCurrentPage") ? undefined : json["nbIemsOnCurrentPage"],
    results: !exists(json, "results")
      ? undefined
      : json["results"] === null
      ? null
      : (json["results"] as Array<any>).map(OrderGridDtoFromJSON)
  };
}

export function OrderGridDtoPaginatedResultsToJSON(value?: OrderGridDtoPaginatedResults | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    currentPage: value.currentPage,
    pageSize: value.pageSize,
    totalCount: value.totalCount,
    results:
      value.results === undefined
        ? undefined
        : value.results === null
        ? null
        : (value.results as Array<any>).map(OrderGridDtoToJSON)
  };
}
