// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  EReferentialTypes,
  EReferentialTypesFromJSON,
  EReferentialTypesFromJSONTyped,
  EReferentialTypesToJSON,
  ReferentialItemDto,
  ReferentialItemDtoFromJSON,
  ReferentialItemDtoFromJSONTyped,
  ReferentialItemDtoToJSON
} from "./";

/**
 *
 * @export
 * @interface ReferentialResultInfoDto
 */
export interface ReferentialResultInfoDto {
  /**
   *
   * @type {EReferentialTypes}
   * @memberof ReferentialResultInfoDto
   */
  type?: EReferentialTypes;
  /**
   *
   * @type {Array<ReferentialItemDto>}
   * @memberof ReferentialResultInfoDto
   */
  list?: Array<ReferentialItemDto> | null;
}

export function ReferentialResultInfoDtoFromJSON(json: any): ReferentialResultInfoDto {
  return ReferentialResultInfoDtoFromJSONTyped(json, false);
}

export function ReferentialResultInfoDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ReferentialResultInfoDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, "type") ? undefined : EReferentialTypesFromJSON(json["type"]),
    list: !exists(json, "list")
      ? undefined
      : json["list"] === null
      ? null
      : (json["list"] as Array<any>).map(ReferentialItemDtoFromJSON)
  };
}

export function ReferentialResultInfoDtoToJSON(value?: ReferentialResultInfoDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: EReferentialTypesToJSON(value.type),
    list:
      value.list === undefined
        ? undefined
        : value.list === null
        ? null
        : (value.list as Array<any>).map(ReferentialItemDtoToJSON)
  };
}
