// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReferentialItemDto
 */
export interface ReferentialItemDto {
  /**
   *
   * @type {string}
   * @memberof ReferentialItemDto
   */
  displayValue?: string | null;
  /**
   *
   * @type {string}
   * @memberof ReferentialItemDto
   */
  keyValue?: string | null;
  /**
   *
   * @type {string}
   * @memberof ReferentialItemDto
   */
  idValue?: string | null;
}

export function ReferentialItemDtoFromJSON(json: any): ReferentialItemDto {
  return ReferentialItemDtoFromJSONTyped(json, false);
}

export function ReferentialItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferentialItemDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    displayValue: !exists(json, "displayValue") ? undefined : json["displayValue"],
    keyValue: !exists(json, "keyValue") ? undefined : json["keyValue"],
    idValue: !exists(json, "idValue") ? undefined : json["idValue"]
  };
}

export function ReferentialItemDtoToJSON(value?: ReferentialItemDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    displayValue: value.displayValue,
    keyValue: value.keyValue,
    idValue: value.idValue
  };
}
