// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  AuthenticateDto,
  AuthenticateDtoFromJSON,
  AuthenticateDtoToJSON,
  UserDto,
  UserDtoFromJSON,
  UserDtoToJSON
} from "../models";

export interface UsersApiUsersAuthenticatePostRequest {
  AuthenticateDto?: AuthenticateDto;
}

/**
 * no description
 */
export class UsersApi extends runtime.BaseAPI {
  /**
   */
  async usersAuthenticatePostRaw(
    requestParameters: UsersApiUsersAuthenticatePostRequest
  ): Promise<runtime.ApiResponse<UserDto>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
    }

    const response = await this.request({
      path: `/Users/authenticate`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: AuthenticateDtoToJSON(requestParameters.AuthenticateDto)
    });

    return new runtime.JSONApiResponse(response, jsonValue => UserDtoFromJSON(jsonValue));
  }

  /**
   */
  async usersAuthenticatePost(requestParameters: UsersApiUsersAuthenticatePostRequest): Promise<UserDto> {
    const response = await this.usersAuthenticatePostRaw(requestParameters);
    return await response.value();
  }
}
